---
title: "Data Analysis Experiment 1"
author: "Paul Jänsch, Alexander Prochnow, Ludger Masch, Pia Stermann"
date: '`r format(Sys.Date(), "%d.%m.%Y")`'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  warning = FALSE, 
  message = FALSE 
)
```

```{r echo=FALSE}
library(tidyverse)

library(aida)

library(brms)

# use the aida-theme for plotting
theme_set(theme_aida())

# these options help Stan run faster
options(mc.cores = parallel::detectCores())

# global color scheme / non-optimized
project_colors = c("#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7", "#000000")

# setting theme colors globally
scale_colour_discrete <- function(...) {
  scale_colour_manual(..., values = project_colors)
}
scale_fill_discrete <- function(...) {
   scale_fill_manual(..., values = project_colors)
} 
```

# Analysis experiment 1

## Import data

```{r}
# insert the actual data here after the main experiment finished
raw_data <- read.csv('../../data/03_main/results_169_main_Size_and_Space_exp1_replication_Group1XPLab2020.csv')
glimpse(raw_data)
```

## Optional data summary

```{r}
# comments
raw_data %>% 
  pull(comments) %>% 
  unique

# age statistics
raw_data %>% 
  select(age) %>% 
  summarize(minAge = min(age),
            meanAge = mean(age),
            maxAge = max(age))

# languages
raw_data %>% 
  pull(languages) %>% 
  unique

# number of participants reporting technical issues
raw_data %>%
  filter(technical_issues=="Yes") %>% 
  select(submission_id) %>% 
  unique %>% 
  count

# comments of technical issue participants
raw_data %>% 
  filter(technical_issues == "Yes") %>% 
  pull(comments) %>% 
  unique()

# gender
raw_data %>% 
  group_by(submission_id) %>% 
  select(gender) %>% 
  unique %>% 
  group_by(gender) %>% 
  count

# education
#raw_data %>% 
#  group_by(submission_id) %>% 
#  select(education) %>% 
#  unique %>% 
#  group_by(education) %>% 
#  count

# handedness
raw_data %>% 
  group_by(submission_id) %>% 
  select(Handedness) %>% 
  unique %>% 
  group_by(Handedness) %>% 
  count
```

## Preprocessing

```{r}

data <- raw_data %>%
  # filter out test trials and distraction task
  filter(trial_type=="experimental_trials_compatible" | trial_type=="experimental_trials_incompatible") %>% 
  # filter out incorrect responses
  filter(correctness==1) %>% 
  # filter out reaction times below 100ms and above 1500ms
  filter(RT>=100) %>% 
  filter(RT<=1500) %>% 
  # log-transform reaction time
  mutate(logRT = log(RT)) %>% 
  # filter out participants who spent more than 25min on the entire experiment (post-prereg decision)
  filter(timeSpent <= 25) %>% 
  # filter out participants with mixed-handedness (post-prereg decision)
  filter(Handedness != "mixed-handedness") %>% 
  # select only factors important for further study
  select(submission_id, trial_type, trial_number, key_pressed, Response, correctness, RT, logRT, Mapping, expected, Handedness) %>% 
  # rename participant column
  rename(Participant=submission_id)

# extract data coming from right-handed participants only
data_right <- data %>% 
  filter(Handedness == "right-handed")

# extract data coming from left-handed participants only
data_left <- data %>% 
  filter(Handedness == "left-handed")


# create dataset which contains the same number of right- and left-handed participants (for hypothesis 7): 

# number of left-handed participants
n_left <- data_left %>%
  select(Participant) %>% 
  unique() %>% 
  count() %>% 
  as.numeric()

# number of participants
n <- data %>%
  select(Participant) %>% 
  unique() %>% 
  count() %>% 
  as.numeric()

# select n_left random right-handed participants
rnd_slice <- sample(1:(n-n_left), n_left, replace = F)

selected_right_participants <- data_right %>%
  select(Participant) %>% 
  unique() %>% 
  slice(rnd_slice) %>% 
  as.list()

# merge the n_left right-handed participants and the n_left left-handed participants
data_both <- data %>% filter(Participant == -1)

for (p in unlist(selected_right_participants)){
  data_both <- rbind(data_both, data %>% filter(Participant == p))
}

data_both <- rbind(data_both, data_left)

```

## Plotting Mean RTs 

```{r}

# aggregating dataset
data_agg <- data %>% 
  group_by(Mapping, Response, Handedness) %>% 
  summarize(meanRT = mean(RT),
            variance = var(RT),
            sd = sd(RT),
            se = sqrt(variance / length(RT))) # standard error = standard deviation of the sampling distribution


# plotting the maen reaction times and the stadard errors for each combination of mapping, handedness and response side
ggplot(data=data_agg, aes(x=Response, y=meanRT, fill=Mapping)) +
  geom_errorbar(aes(ymin=meanRT-se, ymax=meanRT+se), width=0.5, position=position_dodge2(padding=0.5)) +
  geom_col(position="dodge", width=0.5) +
  coord_cartesian(ylim=c(350, 600)) +
  facet_wrap(. ~ Handedness) + 
  ylab("meanRT and SE") + 
  ggtitle("Mean Reaction Time by Handedness", subtitle="Error Bars represent the Standard Error") +
  theme(plot.title = element_text(hjust = 0.5), plot.subtitle=element_text(hjust = 0.5)) # center titles

```


# Hypothesis testing

```{r, results='hide'}

# create brm to check for hypotheses 1-3 (right-handed participants)
model_right <- brm(
  formula = logRT ~ Mapping * Response +
           (Response || Participant),
  data = data_right,
  family = "student"
)

# create brm to check for hypotheses 4-6 (left-handed participants)
model_left <- brm(
  formula = logRT ~ Mapping * Response +
           (Response || Participant),
  data = data_left,
  family = "student"
)

# create brm to check for hypothesis 7
model_both <- brm(
  formula = logRT ~ Mapping * Handedness +
           (1 || Participant),
  data = data_both,
  family = "student"
)

```

```{r}
# inspect model output:

model_right
model_left
model_both

# verify model fit:

pp_check(model_right)

pp_check(model_left)

pp_check(model_both)

```

```{r}

# general approach: We will use the 'hypothesis' function of the brms-package to evaluate the hypotheses. This function uses the posterior samples of our brm to determine the proportion of samples supporting the hypothesis. This proportion is then transformed into an evidence ratio aka Bayes factor.

# H1: Right-handed participants response times' for right-hand responses are faster to the larger stimulus than to the smaller stimulus.
h1 <- hypothesis(model_right, "exp(Intercept + Responseright) < exp(Intercept + Mappingincompatible + Responseright + Mappingincompatible:Responseright)")
print(h1, digits = 4)

# H2: Right-handed participants left-hand responses' are faster to the smaller stimulus than to the larger stimulus.
h2 <- hypothesis(model_right, "exp(Intercept) < exp(Intercept + Mappingincompatible)")
print(h2, digits = 4)

# H3: The stimulus size – response location compatibility effect in right-handed participants is larger for right-hand responses than for left-hand responses.
h3 <- hypothesis(model_right, "exp(Intercept + Mappingincompatible + Responseright + Mappingincompatible:Responseright) - exp(Intercept + Responseright) > exp(Intercept + Mappingincompatible) - exp(Intercept)")
print(h3, digits = 4)

# H4: Left-handed participants response times' for left-hand responses are faster to the larger stimulus than to the smaller stimulus.
h4 <- hypothesis(model_left, "exp(Intercept + Mappingincompatible) < exp(Intercept)")
print(h4, digits = 4)

# H5: Left-handed participants response times' for right-hand responses are faster to the smaller stimulus than to the larger stimulus.
h5 <- hypothesis(model_left, "exp(Intercept + Mappingincompatible + Responseright + Mappingincompatible:Responseright) < exp(Intercept + Responseright)")
print(h5, digits = 4)

# H6: The stimulus size – response location compatibility effect in left-handed participants is larger for left-hand responses than for right-hand responses.
h6 <- hypothesis(model_left, "exp(Intercept) - exp(Intercept + Mappingincompatible) > exp(Intercept + Responseright) - exp(Intercept + Mappingincompatible + Responseright + Mappingincompatible:Responseright)")
print(h6, digits = 4)

# H7: The stimulus size- response location compatibility effect is larger for right-handed compared to left-handed people. I.e., the absolute difference between response times in the compatible condition and response times in the incompatible condition is larger for right-handed compared to left-handed people.
h7 <- hypothesis(model_both, "abs(exp(Intercept + Mappingincompatible) - exp(Intercept)) < abs(exp(Intercept + Mappingincompatible + HandednessrightMhanded + Mappingincompatible:HandednessrightMhanded) - exp(Intercept + HandednessrightMhanded))")
print(h7, digits = 4)


# exploratory hypotheses for left-handed participants to quantify the effect size:

# H8: Left-handed participants left-hand responses' are faster to the smaller stimulus than to the larger stimulus
h8 <- hypothesis(model_left, "exp(Intercept) < exp(Intercept + Mappingincompatible)")
print(h8, digits = 4)

# H9: Left-handed participants response times' for right-hand responses are faster to the larger stimulus than to the smaller stimulus.
h9 <- hypothesis(model_left, "exp(Intercept + Responseright) < exp(Intercept + Mappingincompatible + Responseright + Mappingincompatible:Responseright)")
print(h9, digits = 4)


```

