---
title: "Data Analysis Experiment 1"
author: "Paul Jänsch, Alexander Prochnow, Ludger Masch, Pia Stermann"
date: '`r format(Sys.Date(), "%d.%m.%Y")`'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  warning = FALSE, 
  message = FALSE 
)
```

```{r echo=FALSE}
library(tidyverse)

library(aida)

library(brms)

# use the aida-theme for plotting
theme_set(theme_aida())

# these options help Stan run faster
options(mc.cores = parallel::detectCores())

# global color scheme / non-optimized
project_colors = c("#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7", "#000000")

# setting theme colors globally
scale_colour_discrete <- function(...) {
  scale_colour_manual(..., values = project_colors)
}
scale_fill_discrete <- function(...) {
   scale_fill_manual(..., values = project_colors)
} 
```

# Optional data summary for main experiment

## Import data

```{r}
# insert the actual data here after the main experiment finished
raw_data <- read.csv('../../data/03_main/results_169_main_Size_and_Space_exp1_replication_Group1XPLab2020.csv')
glimpse(raw_data)
```

## Optional data summary

```{r}
# comments
raw_data %>% 
  pull(comments) %>% 
  unique

# age statistics
raw_data %>% 
  select(age) %>% 
  summarize(minAge = min(age),
            meanAge = mean(age),
            maxAge = max(age))

# average time spent
raw_data %>% 
  select(timeSpent) %>% 
  summarize(minTimeSpent = min(timeSpent),
            meanTimeSpent = mean(timeSpent),
            maxTimeSpent = max(timeSpent))

# languages
raw_data %>% 
  pull(languages) %>% 
  unique

# number of participants reporting technical issues
raw_data %>%
  group_by(technical_issues) %>% 
  select(submission_id, technical_issues) %>% 
  unique %>% 
  count

# description of technical problems
raw_data %>% 
  filter(technical_issues=="Yes") %>% 
  pull(comments) %>% 
  unique

# gender
raw_data %>% 
  group_by(gender) %>% 
  select(submission_id, gender) %>% 
  unique %>% 
  count

# handedness
raw_data %>% 
  group_by(Handedness) %>% 
  select(submission_id, Handedness) %>% 
  unique %>% 
  count

raw_data %>% 
  filter(str_detect(comments, "toaster"))

raw_data %>% 
  filter(Handedness=="mixed-handedness") %>% 
  pull(submission_id) %>% unique

below <- function(threshold, val) {
  return(map_lgl(val, function(input) {
    if(input<threshold) return(TRUE) else return(FALSE)
  }))
}


timeData <- raw_data %>% 
  select(timeSpent) %>% 
  unique %>% 
  mutate(below25=below(25, timeSpent))

timeData %>% 
  ggplot(aes(x=seq(1,72,1),y=timeSpent)) + 
  geom_point(aes(color=below25)) +
  geom_line() + 
  xlab("Participant") +
  geom_hline(aes(yintercept=25))

```

## Term paper plots

```{r}
# gender statistics
gender_data <- raw_data %>% 
  group_by(gender) %>% 
  select(submission_id, gender) %>% 
  unique %>% 
  count
gender_summary<- gender_data %>% 
  pivot_wider(names_from=gender, values_from=n)

# age statistics
age_data <- raw_data %>% 
  group_by(submission_id) %>% 
  select(submission_id, age, Handedness) %>% 
  unique
age_summary <- raw_data %>% 
  select(age) %>% 
  summarize(minAge = min(age),
            meanAge = round(mean(age), digits=2),
            maxAge = max(age))

# handedness statistics
handedness_data <- raw_data %>% 
  group_by(Handedness) %>% 
  select(submission_id, Handedness) %>% 
  unique %>% 
  count
handedness_summary <- handedness_data %>% 
  pivot_wider(names_from=Handedness, values_from=n)

# example barplots:

# gender barplot
gender_data %>% 
  ggplot(aes(x=gender, y=n, fill=gender)) + 
  geom_col(width=0.5) +
  geom_text(aes(y=n+5, label=n), color="black", size=6) + # str_c(n, , substr(gender, 1, 1))
  ggtitle("Gender distribution") +
  theme(plot.title = element_text(hjust = 0.5), legend.position = "none")
  
# handedness barplot
handedness_data %>% 
  ggplot(aes(x=Handedness, y=n, fill=Handedness)) + # to order after value use x=reorder(Handedness, -n)
  geom_col(width=0.5) +
  geom_text(aes(y=n+5, label=n), color="black", size=6) + 
  ggtitle("Handedness distribution") +
  theme(plot.title = element_text(hjust = 0.5), legend.position = "none")

# age plot
age_data %>% 
  ggplot(aes(x=age, fill=Handedness)) +
  geom_histogram(binwidth = 0.5) +
  ggtitle("Age distribution") +
  theme(plot.title = element_text(hjust = 0.5))

base_data <- raw_data %>% 
  filter(trial_type=="experimental_trials_compatible" | trial_type=="experimental_trials_incompatible") %>% 
  filter(correctness==1) %>% 
  filter(timeSpent<25) %>% 
  filter(Handedness!="mixed-handedness")

RT_range <- function(val) {
  return(map_lgl(val, function(v) {
    if(v>100 & v<1500) return(TRUE) else return(FALSE)
  }))
}

base_data$in_range <- base_data$RT %>% 
  RT_range()

n_in_range <- base_data %>% 
  group_by(in_range) %>% 
  count %>% 
  pivot_wider(names_from = in_range, values_from = n)



base_data %>% 
  ggplot(aes(x=age, y=RT, color=in_range)) + 
  geom_point() + 
  labs(title="RT by Age", subtitle=str_c("Filtered out ", n_in_range$"FALSE", ", Kept ", n_in_range$"TRUE"))

age_count <- base_data %>% 
  group_by(age) %>% 
  select(age, submission_id) %>% 
  unique %>% 
  count
# examples for meanRT by Age:
meanRT_summary <- base_data %>% 
  group_by(age) %>% 
  summarize(meanRT=mean(RT))
# suggestion1
meanRT_summary %>% 
  merge(age_count) %>% 
  ggplot(aes(x=age, y=meanRT)) + 
  geom_line() +
  geom_point(aes(color=n)) +
  labs(title="Mean Reaction Time by Age", subtitle="n indicates number of participants of that age") + 
  theme(plot.title = element_text(hjust = 0.5), plot.subtitle=element_text(hjust = 0.5)) # center titles

# suggestion2
base_data %>% 
  ggplot(aes(x=age, y=RT), group=age) +
  geom_point(alpha=0.05) +
  ylim(100, 1500) +
  geom_line(data=meanRT_summary, mapping=aes(x=age, y=meanRT), color="orange") +
  labs(title="RT of all experimental trials and Mean RT by Age") +
  annotate("text", x=30, y=650, label="meanRT", size=3) + 
  annotate("rect", xmin=28, xmax=32, ymin=620, ymax=680, alpha=0.1, color="orange")

```


## Preprocessing

```{r}

data <- raw_data %>%
  # filter out test trials and distraction task
  filter(trial_type=="experimental_trials_compatible" | trial_type=="experimental_trials_incompatible") %>%
  # filter out mixed-handed participants (1 participant)
  filter(Handedness!="mixed-handedness") %>% 
  # filter out participants that spent 25 minutes or more on the experiment
  # (3 participants: 42.1min, 142.49min, 245.54min)
  filter(timeSpent<25) %>% 
  # filter out incorrect responses
  filter(correctness==1) %>% 
  # filter out reaction times below 100ms and above 1500ms
  filter(RT>=100) %>% 
  filter(RT<=1500) %>% 
  # log-transform reaction time
  mutate(logRT = log(RT)) %>% 
  # select only factors important for further study
  select(submission_id, trial_type, trial_number, key_pressed, Response, correctness, RT, logRT, Mapping, expected, Handedness) %>% 
  # rename participant column
  rename(Participant=submission_id)

# extract data coming from right-handed participants only
data_right <- data %>% 
  filter(Handedness == "right-handed")

# extract data coming from left-handed participants only
data_left <- data %>% 
  filter(Handedness == "left-handed")


# create dataset which contains the same number of right- and left-handed participants (for hypothesis 7): 

# number of left-handed participants
n_left <- data_left %>%
  select(Participant) %>% 
  unique() %>% 
  count() %>% 
  as.numeric()

# number of participants
n <- data %>%
  select(Participant) %>% 
  unique() %>% 
  count() %>% 
  as.numeric()

# select n_left random right-handed participants
rnd_slice <- sample(1:(n-n_left), n_left, replace = F)

selected_right_participants <- data_right %>%
  select(Participant) %>% 
  unique() %>% 
  slice(rnd_slice) %>% 
  as.list()

# merge the n_left right-handed participants and the n_left left-handed participants
data_both <- data %>% filter(Participant == -1)

for (p in unlist(selected_right_participants)){
  data_both <- rbind(data_both, data %>% filter(Participant == p))
}

data_both <- rbind(data_both, data_left)

```

## Plotting Mean RTs 

```{r}

# aggregating dataset
data_agg <- data %>% 
  group_by(Mapping, Response, Handedness) %>% 
  summarize(meanRT = mean(RT),
            variance = var(RT),
            sd = sd(RT),
            se = sqrt(variance / length(RT))) # standard error = standard deviation of the sampling distribution


# plotting the maen reaction times and the stadard errors for each combination of mapping, handedness and response side
ggplot(data=data_agg, aes(x=Response, y=meanRT, fill=Mapping)) +
  geom_errorbar(aes(ymin=meanRT-se, ymax=meanRT+se), width=0.5, position=position_dodge2(padding=0.5)) +
  geom_col(position="dodge", width=0.5) +
  coord_cartesian(ylim=c(350, 600)) +
  facet_wrap(. ~ Handedness) + 
  ylab("meanRT and SE") + 
  ggtitle("Mean Reaction Time by Handedness", subtitle="Error Bars represent the Standard Error") +
  theme(plot.title = element_text(hjust = 0.5), plot.subtitle=element_text(hjust = 0.5)) # center titles

# using Local Polynomial Regression Fitting (loess) to fit curves to reaction time data
data %>% 
  filter(Handedness=="left-handed") %>% 
  ggplot(aes(x=trial_number, y=RT, color=Mapping)) +
  geom_smooth(alpha=0.1, method="loess") +
  facet_wrap(. ~ Response) +
  labs(title="Left-handed")

data %>% 
  filter(Handedness=="right-handed") %>% 
  ggplot(aes(x=trial_number, y=RT, color=Mapping)) +
  geom_smooth(alpha=0.1, method="loess") +
  facet_wrap(. ~ Response) +
  labs(title="Right-handed") 

```

## Inspecting mixed-handedness

```{r}
mixed_handed_data <- raw_data %>% 
  filter(Handedness=="mixed-handedness") %>% 
   # filter out test trials and distraction task
  filter(trial_type=="experimental_trials_compatible" | trial_type=="experimental_trials_incompatible") %>%
  # filter out participants that spent 25 minutes or more on the experiment
  # (3 participants: 42.1min, 142.49min, 245.54min)
  filter(timeSpent<25) %>% 
  # filter out incorrect responses
  filter(correctness==1) %>% 
  # filter out reaction times below 100ms and above 1500ms
  filter(RT>=100) %>% 
  filter(RT<=1500) %>% 
  # select only factors important for further study
  select(submission_id, trial_type, trial_number, key_pressed, Response, correctness, RT, Mapping, expected, Handedness) %>% 
  # rename participant column
  rename(Participant=submission_id)

mixed_handed_summary <- mixed_handed_data %>% 
  group_by(trial_type, Response) %>% 
  summarize(meanRT=mean(RT),
            medRT=median(RT))

mixed_handed_data %>% 
  ggplot(aes(x=trial_number, y=RT, color=trial_type)) +
  geom_point() +
  geom_line() +
  geom_hline(data=mixed_handed_summary, aes(yintercept=medRT, color=trial_type), linetype="dashed") +
  labs(title="Reaction Time accross experimental trials", subtitle="separate for both conditions, dashed lines signifying medianRT per condition") +
  facet_wrap(. ~ Response)
```

