---
title: "Data Analysis Experiment 1"
author: "Paul Jänsch, Alexander Prochnow, Ludger Masch, Pia Stermann"
date: '`r format(Sys.Date(), "%d.%m.%Y")`'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  warning = FALSE, 
  message = FALSE 
)
```

```{r echo=FALSE}
library(tidyverse)

library(aida)

library(brms)

# use the aida-theme for plotting
theme_set(theme_aida())

# global color scheme / non-optimized
project_colors = c("#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7", "#000000")

# setting theme colors globally
scale_colour_discrete <- function(...) {
  scale_colour_manual(..., values = project_colors)
}
scale_fill_discrete <- function(...) {
   scale_fill_manual(..., values = project_colors)
} 
```

# Analysis experiment 1

## Import data

```{r}
raw_data <- read.csv('results_165_pilot_Size_and_Space_exp1_replication_Group1XPLab2020.csv')
glimpse(raw_data)
```

## Preprocessing

```{r}
# Filter out reaction times below 100ms and above 1500ms
data <- raw_data %>%
  filter(trial_type=="experimental_trials_compatible" | trial_type=="experimental_trials_incompatible") %>% 
  filter(RT>=100) %>% 
  filter(RT<=1500) %>% 
  mutate(logRT = log(RT)) %>% 
  select(submission_id, trial_type, trial_number, key_pressed, Response, correctness, RT, logRT, Mapping, expected, handedness) %>% 
  rename(Participant=submission_id)
```

## Plotting Mean RTs 

```{r}
data_agg <- data %>% 
  group_by(Mapping, Response, handedness) %>% 
  summarize(meanRT = mean(RT),
            variance = var(RT),
            sd = sd(RT),
            se = sqrt(variance / length(RT))) # standard error = standard deviation of the sampling distribution

ggplot(data=data_agg, aes(x=Response, y=meanRT, fill=Mapping)) +
  geom_errorbar(aes(ymin=meanRT-se, ymax=meanRT+se), width=0.5, position=position_dodge2(padding=0.5)) +
  geom_col(position="dodge", width=0.5) +
  coord_cartesian(ylim=c(350, 600)) +
  facet_wrap(. ~ handedness) + 
  ylab("meanRT and SE") + 
  ggtitle("Mean Reaction Time by Handedness", subtitle="Error Bars represent the Standard Error") +
  theme(plot.title = element_text(hjust = 0.5), plot.subtitle=element_text(hjust = 0.5)) # center titles

```


# Hypothesis testing

```{r}

model <- brm(
  formula = logRT ~ Mapping * Response +
           (Response || Participant),
  data = data
)

model

```

```{r}

# H1: Response times for right-hand responses are faster to the larger stimulus than to the smaller stimulus.
h1 <- hypothesis(model, "Intercept + Responseright < Intercept + Mappingincompatible + Responseright + Mappingincompatible:Responseright")
print(h1, digits = 4)

# H2: Left-hand responses are faster to the smaller stimulus than to the larger stimulus.
h2 <- hypothesis(model, "Intercept < Intercept + Mappingincompatible")
print(h2, digits = 4)

# H3: The stimulus size – response location compatibility effect is larger for right-hand responses than for left-hand responses.
h3 <- hypothesis(model, "Intercept + Mappingincompatible + Responseright + Mappingincompatible:Responseright - (Intercept + Responseright) > Intercept + Mappingincompatible - (Intercept)")
print(h3, digits = 4)

```

